-- +goose Up
CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dn VARCHAR(64) UNIQUE NOT NULL,
    api_key VARCHAR(128) UNIQUE NOT NULL DEFAULT LOWER(CONCAT(SHA2(UUID(), 256), SHA2(UUID(), 256)))
);

-- +goose Down
DROP TABLE users;
